### PR TITLE
feat: save window state when closing agent

### LINKED ISSUE #659: Remember window size
I have a pretty big monitor (3440x1440) and when starting the agent app it automatically expands to fill the screen (OSX, haven't tried it anywhere else). Having a more reasonable initial size, and potentially remembering the previous layout, would be a lot less jarring

### PR DESCRIPTION
**Pull request by ert78gb**
close #659

### CODE REVIEW

**Comment by mondalaci** [comment]
The linter is not happy about this, so CI failed.

**Comment by ert78gb** [comment]
sry, fixed

**Comment by mondalaci** [comment]
I set the window to non-maximized state, exit Agent, and when I relaunced Agent, the window didn't appear again. This is the relevant part of the log:

```
laci@spark:~/projects/agent$ npm run electron

> uhk-agent@1.2.13 electron /home/laci/projects/agent
> lerna exec --scope uhk-agent npm start

lerna notice cli v3.2.0
lerna info filter [ 'uhk-agent' ]
lerna info Executing command in 1 package: "npm start"

> uhk-agent@0.0.0 start /home/laci/projects/agent/packages/uhk-agent
> electron ./dist/electron-main.js

[01:56:35.795] [info] [Electron Main] Create new window.
[01:56:35.799] [info] [Electron Main] packagesDir: /home/laci/projects/agent/tmp
[01:56:35.800] [info] [WindowState] load settings
[01:56:35.801] [info] [WindowState] loaded settings {"x":0,"y":109,"width":1,"height":1,"isMaximized":false,"isFullScreen":false}
[01:56:35.801] [info] [WindowState] loaded settings is visible true
[01:56:35.802] [info] [WindowState] return with loaded settings
....
```

By the way, where can I find the configuration file that stores this information on Linux?

**Comment by ert78gb** [comment]
Very interest. The `width` and `height` of the window is 1. We log the save windows state object to. Pls next time include the last lines of the logs.

We use the [electron-settings](https://github.com/nathanbuchar/electron-settings/) to persist user configurations, this lib store the settings https://github.com/nathanbuchar/electron-settings/wiki/FAQs#where-is-the-settings-file-saved

**Comment by ert78gb** [comment]
@mondalaci if you have time pls review my prev comment. thx

**Pull request merged**
