### PR TITLE
Package.json - Tslint and Stylelint fixes

### PR DESCRIPTION
**Pull request by NejcZdovc**
Fixed ts linter for windows and added style linter into dependencies. Renamed deprecated rule from **number-zero-length-no-unit** to **length-zero-no-unit**. 

@fjozsef is this working on linux as well?

### CODE REVIEW

**Comment by fjozsef** [comment]
Unfortunately it doesn't wok on linux. It needs the parameters as string (between apostrophe or quotation mark).
And there is an other problem, if there is any error in the first path, then the second one isn't evaluated. 
We should run a single tslint command with multiple path.

**Comment by NejcZdovc** [comment]
Ok, will try to find out another approach to make it work

**Comment by fjozsef** [comment]
Okay and don't forget to rebase.

**Comment by fjozsef** [comment]
We should either find a way to make it work on both windows and linux or postpone the fix later and close this.

**Comment by NejcZdovc** [comment]
Let's close it for now

**Pull request closed without merging**
