### PR TITLE
feat: command macro action

### PR DESCRIPTION
**Pull request by ert78gb**
close: #1534

### CODE REVIEW

**Comment by kareltucek** [comment]
Would it be possible to show the commands, ideally preserving lines? Current situation is not exactly ideal:

2021-08-23-150351_2541x2104_scrot

**Comment by ert78gb** [comment]
Sorry @kareltucek but I don't understand your question. Would you like to see the `Command: <typed text ....>` ?

**Comment by kareltucek** [comment]
> Sorry @kareltucek but I don't understand your question. Would you like to see the `Command: <typed text ....>` ?

Yes. And if the text is multiline, I would love to see something like:
```
Command: Some line 1
                  Another line 2
                  And one more line
```
rather than freeflow:
```
Command: Some line 1Another line 2And one more line
```
(Which is the way text action is rendered.)

**Comment by ert78gb** [comment]
@mondalaci what do you think about it?

**Comment by kareltucek** [comment]
Also, if I try to delete some macro, the macro does not dissapear and save button does not show up.

```
14:35:34.437 › [DeviceRendererService] dispatch action [user-config] Load User Config from Device reply
14:35:34.556 › [UhkHidDevice] Available devices unchanged
14:35:34.620 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
14:35:35.238 › [AppEffects] navigate to { commands: [ '/' ] }
14:35:47.050 › RangeError: "value" argument is out of bounds
    at E (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1770838)
    at Uint8Array.a.writeUInt8 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1779407)
    at r.writeUInt8 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1292585)
    at o.toBinary (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1577190)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1722180
    at r.writeArray (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1294671)
    at o.toBinary (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1722141)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:201757
    at r.writeArray (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1294671)
    at r.toBinary (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:201723)
14:35:47.108 › TypeError: Cannot read property 'id' of undefined
    at o.fromJsonObjectV1 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1577428)
    at o.fromJsonObject (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1576731)
    at Function.fromJSONObjectV1 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1843528)
    at Function.fromJSONObject (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1842897)
    at Function.createKeyAction (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1841604)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1722577
    at Array.map (<anonymous>)
    at o.fromJsonObjectV1 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1722552)
    at o.fromJsonObject (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1721610)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:202079
14:35:47.110 › TypeError: Cannot read property 'id' of undefined
    at o.fromJsonObjectV1 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1577428)
    at o.fromJsonObject (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1576731)
    at Function.fromJSONObjectV1 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1843528)
    at Function.fromJSONObject (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1842897)
    at Function.createKeyAction (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1841604)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1722577
    at Array.map (<anonymous>)
    at o.fromJsonObjectV1 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1722552)
    at o.fromJsonObject (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1721610)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:202079
14:35:47.113 › TypeError: Cannot read property 'usageCount' of undefined
    at Mb (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:796638)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:796987
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1615495
    at memoized (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1615069)
    at ue (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1615830)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1615547
    at memoized (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1615069)
    at o.project (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1614723)
    at o._next (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1621892)
    at o.next (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:154839)
14:35:47.115 › TypeError: Cannot read property 'id' of undefined
    at o.fromJsonObjectV1 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1577428)
    at o.fromJsonObject (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1576731)
    at Function.fromJSONObjectV1 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1843528)
    at Function.fromJSONObject (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1842897)
    at Function.createKeyAction (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1841604)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1722577
    at Array.map (<anonymous>)
    at o.fromJsonObjectV1 (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1722552)
    at o.fromJsonObject (file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:1721610)
    at file:///opt/firmware/lib/agent/packages/uhk-agent/dist/renderer/main-es2015.db9dfd3e1bd9967490f3.js:1:202079
```

**Comment by mondalaci** [comment]
@ert78gb I like Karel's suggestion, including multiline display.

**Comment by ert78gb** [comment]
It looks like “data error”.  For some reason it wanna write larger than 255 value in a uint8 .

If you share the user-config I can debug it. Or enough if you write the reproduction steps

**Comment by mondalaci** [comment]
@ert78gb Please resolve the conflicts.

**Comment by ert78gb** [comment]
@mondalaci the conflict has been resolved

**Pull request merged**
