### PR TITLE
feat: add more layers

### PR DESCRIPTION
**Pull request by ert78gb**
close: #617

### CODE REVIEW

**Comment by kareltucek** [comment]
I wanted to try this branch out, but I am getting this result:

2021-08-21-135713_2508x2105_scrot

Any ideas what I am doing wrong?

**Comment by mondalaci** [comment]
@kareltucek You are doing everything right. Let me talk to @ert78gb about when should the update screen trigger, and possibly how to ignore it.

**Comment by ert78gb** [comment]
If the user config version of the right module is greater than the userConfig version of the agent then this screen will visible.
If you build agent from source you can change the `userConfigVersion` in the root package.json file

**Comment by kareltucek** [comment]
Allright, got it running!

Some notes:
- When I add fifth layer (fn2), its checkbox does not get checked until I switch to another keymap and back.
- If I merge command-action branch with more-layer branch, run agent, and try to load config that contains some macro commands, agent does not like it. The config seems to load fine, but save button does not appear and console is full of logs:

2021-08-22-233504_3840x2160_scrot

**Comment by ert78gb** [comment]
Both PR have affect to the user-config I don't know how compatible them. Would we like to merge them at once or do we merge them incrementally?

**Comment by kareltucek** [comment]
Incrementally, unless Laszlo changes his mind. Which means that it is indeed nonissue at the moment.

**Comment by mondalaci** [comment]
@kareltucek I'm running [common trunk](https://github.com/UltimateHackingKeyboard/firmware/pull/420), and the extra layers work as intended, but the modifier layers don't trigger the mapped actions. Are they supposed to?

We commented out the force update screen that was present in this PR previously. I didn't originally envision the configuration parser to be backward-compatible which justified it, but now that it's backward-compatible, we'll probably remove the force update Agent screen.

I can't reproduce the Fn2 checkbox issue you mentioned. Can you? Command actions work fine, too.

**Comment by ert78gb** [comment]
How could it be a backward compatibility changes? We inserted the layer id/name field in the middle of the binary structure.

**Comment by mondalaci** [comment]
@ert78gb The configurator parser of the firmware branches according to the user config version number.

**Comment by kareltucek** [comment]
@ert78gb user config version is part of flashed eeprom image, so the firmware can interpret it accordingly.

@mondalaci as far as I remember, added layers are not par of common_trunk. You need common_trunk_upstream, or merge the layer pr separately and wait till it propagates into common_trunk.

> I didn't originally envision the configuration parser to be backward-compatible which justified it, but now that it's backward-compatible, we'll probably remove the force update Agent screen.

Well, this is an opportunity to try out the migration process in practice. If we continue to treat it as a noncompatible upgrade, it will make future config upgrades easier for us.

**Comment by kareltucek** [comment]
(To clarify, I have no set-in-stone intention to maintain the parser compatibility across all future config version upgrades - it just turns out that life is easier with backward compatible parser when there is no strong reason to break the compatibility.)

**Comment by mondalaci** [comment]
@kareltucek I much prefer backward compatibility, assuming that the maintenance burden is light which is according to the code. We can burn the bridges later if the maintenance burden becomes less tolerable or if we run out of flash space.

@ert78gb Please remove the force update Agent screen because we don't need it. Sorry for the extra work!

**Comment by ert78gb** [comment]
np the extra work. I just would like to double check to remove this screen is a good idea.
Currently, Agent parses the user configuration based on the major version number of `userConfigVersion` of the right module.
Agent can only parse those user configurations which were previously implemented. I think Agent should notify the user that a newer version of the Agent will able to parse the user configuration.

The "Update Agent" page is visible because the value of `userConfigVersion` in the package.json is `4.1.0`. The current firmware  returns with `4.2.0` user config version . There is a bug, because only the major version numbers should be compared. I am gonna fix it.

I have 3 use cases:
**Case 1:**
User has multiple computers.
- User upgrades the Agent to the latest version on Machine A
- Upgrade firmware on Machine A
- Connect the keyboard to Machine B
Agent should notify the user about the user config incompatibility.

**Case 2:**
Downgrade Agent
- User upgrades the Agent
- User upgrades the firmware
- User downgrades the Agent
Agent should notify the user about the user config incompatibility.

**Case 3:**
Upgrade with newer firmware
- User downloads the latest alfa firmware
- Upgrade the keyboard with the latest alfa firmware
Agent should notify the user about the user config incompatibility.

**Comment by mondalaci** [comment]
@ert78gb You're right, but I have some things to add.

1. We should check not only majorVersion, but majorVersion.minorVersion because [increasing the minor version extends the configuration with new values](https://github.com/UltimateHackingKeyboard/firmware/blob/master/VERSIONING.md).
2. We should only display the Agent update screen if Agent is unable to parse the user config. A new Agent version may only extend the minor version, but the new configuration values may not be used by the current UHK configuration, so let's not bother the user, only when necessary. The top Agent notification bar will appear anyways, so the user can update Agent if wanted.
3. It's possible that we break an Agent release, and some users want to use an older Agent version until we fix the bug. This should happen quite rarely, but it would be useful to be able to ignore the Agent update screen. Please implement the `--disable-agent-update-screen` for this purpose. This option should also be useful for testing and comparing older Agent versions.

**Pull request merged**
