### PR TITLE
feat: use transparent favicon.ico

### LINKED ISSUE #1223: Update favicon
The favicon of the web build has white sunglasses. The sunglasses should be transparent. We should use the same Agent icon here as at other places.

### PR DESCRIPTION
**Pull request by ert78gb**
close #1223 

I use Mac with the dark mode it is mean the background of the favicon will black. 
Screenshot 2020-04-25 at 19 30 46

### CODE REVIEW

**Comment by mondalaci** [comment]
You are right. The favicon should look good both on bright and dark backgrounds.

See [agent-icon.zip](https://github.com/UltimateHackingKeyboard/agent/files/4534195/agent-icon.zip) which contains the SVG and 1024x1024 PNG version of the gradient Agent logo.

[SVG favicon support is quite poor](https://caniuse.com/#feat=link-icon-svg), so use PNG or ICO format for favicon. I'm not sure about the resolution.

Regarding application icons, use SVG if possible. Otherwise use the provided 1024x1024 resolution PNG because it's [future proof](https://www.visualpharm.com/articles/icon_sizes.html). (The current taskbar icon is lower resolution and looks slightly pixelated on 4K.)

**Comment by mondalaci** [comment]
I've just realized that there was no margin around the icon, so I fixed it. Please use the new 
[agent-icon.zip](https://github.com/UltimateHackingKeyboard/agent/files/4536635/agent-icon.zip) file.

**Comment by ert78gb** [comment]
I replaced the favicon and app icon 
Screenshot 2020-04-27 at 20 43 12
Screenshot 2020-04-27 at 20 42 36

**Comment by mondalaci** [comment]
Please use the newly uploaded [agent-icon.zip](https://github.com/UltimateHackingKeyboard/agent/files/4545837/agent-icon.zip) icons for the application icon and the favicon.

**Comment by mondalaci** [comment]
Please also make a screenshot with light and dark mode.

**Comment by ert78gb** [comment]
The new favicons. If you like it I replace the app icons too.
Screenshot 2020-04-29 at 20 09 00
Screenshot 2020-04-29 at 20 08 38

**Pull request merged**
