### PR TITLE
feat: support more mouse buttons

### PR DESCRIPTION
**Pull request by dgyimesi**
close: #834

### CODE REVIEW

**Comment by mondalaci** [comment]
@dgyimesi When I click on the left button, button 4-8 get toggled.

Untitled

When I click on button 4-8, none of them get toggled.

**Comment by mondalaci** [comment]
@krokofant We can definitely use some help on this. If you want to contribute please [sign the CLA](https://github.com/UltimateHackingKeyboard/agent/blob/master/CONTRIBUTING.md) first. Thanks so much!

**Comment by ert78gb** [comment]
@mondalaci I fixed the multi-button selection and added the Key Action texts.
The question is how to visualize the action on the keyboard?
The left-click visualization
Screenshot 2019-08-21 at 20 40 50
 
Now I just added the number as the text.
Screenshot 2019-08-21 at 20 47 15

**Comment by krokofant** [comment]
Maybe make the button number formated similar to the weight of these mouse actions
image
font-weight:bold and font-size around 30px

Does the mouse buttons 4-8 really exists? I'm not sure what documentation to look at but the Windows docs for [virtual key codes](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) lists left, right, middle, XBUTTON1 and XBUTTON2. I'm wondering what the relationship is between the left, middle, right, XBUTTON1, XBUTTON2 and the ones targeted in this PR.

Would the 4:th button actually be what MS refers to as XBUTTON1? In that case the naming maybe should be `Left`, `Middle`, `Right`, `X1`, `X2`, `X3`, `X4`, `X5`.

**Comment by mondalaci** [comment]
@ert78gb Please only display Button 4-8 in the popover if the user config is greater or equal than 4.1.1. (I'll release a new firmware today.)

@krokofant The buttons are numbered based on their USB representation. See the https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf document, although I can't find the relevant page right now. I'm open to alternative namings as long as they're consistent with what OSes display.

**Comment by mondalaci** [comment]
@krokofant On second thought, I agree that button 4-8 are not intuitive names. Let's leave them the way they are for now, though. Once this PR is merged, we'll be able to trigger these buttons with the UHK and test them with various key capture applications to find more intuitive names.

**Comment by ert78gb** [comment]
@mondalaci I added the 
>  Please only display Button 4-8 in the popover if the user config is greater or equal than 4.1.1.

**Pull request merged**
