### PR TITLE
feat(user-config): Upload user configuration from json/bin file

### PR DESCRIPTION
**Pull request by ert78gb**
close: #455

### CODE REVIEW

**Comment by mondalaci** [comment]
I found the following issues:
1. I cannot choose a .json file, only a .bin file.
2. The configuration doesn't get automatically applied.
3. When uploading an invalid device configuration (I typed some random characters in the bin file) the red error component appears, but it doesn't contain any text. Please make it contain: "Invalid configuration was specified."

**Comment by ert78gb** [comment]
1. Could you create a screenshot about the open file dialog? In browser the filter working. In electron the filter not applied all files selectable. Maybe elector works differently on linux and mac 
2. What do you mean? If user-config successfully loaded to the agent after automatically call the apply to device function, or just show the button? The code do the same as reset user config -> not show button, not apply user config
3. fixed

**Comment by mondalaci** [comment]
1. I think you're probably right and the open dialog doesn't work consistently across OSes. Here's the Linux screenshot:

screenshot from 2018-01-06 10-36-36

2. Reset applies the configuration, but the upload configuration doesn't apply it. I cannot see the Save button appearing.

**Comment by ert78gb** [comment]
@mondalaci done
- I removed the file filter because it works depend from the OS

**Pull request merged**
