### PR TITLE
Fix menu scancode.

### PR DESCRIPTION
**Pull request by mondalaci**

### CODE REVIEW

**Comment by mondalaci** [comment]
@ert78gb I need your help with this. I fixed the scancode of the menu key. Now the problem is that the old menu key (leftwards of the right shift key on the mod layer) scancode is already used in the default keymap and if I try to edit the old menu key scancode in Agent, it hits an infinite loop:

```
[03:06:08.068] [error] [ { TypeError: Cannot read property 'id' of undefined
      at Object.View_KeypressTabComponent_0.i1.ɵvid [as updateDirectives] (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/main.bundle.js:9820:53)
      at Object.debugUpdateDirectives [as updateDirectives] (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/vendor.bundle.js:23887:21)
      at checkAndUpdateView (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/vendor.bundle.js:23071:14)
      at callViewAction (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/vendor.bundle.js:23419:21)
      at execComponentViewsAction (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/vendor.bundle.js:23351:13)
      at checkAndUpdateView (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/vendor.bundle.js:23077:5)
      at callViewAction (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/vendor.bundle.js:23419:21)
      at execEmbeddedViewsAction (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/vendor.bundle.js:23377:17)
      at checkAndUpdateView (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/vendor.bundle.js:23072:5)
      at callViewAction (file:///home/laci/projects/agent/packages/uhk-agent/dist/renderer/vendor.bundle.js:23419:21)
    ngDebugContext: 
     DebugContext_ {
       view: [Object],
       nodeIndex: 6,
       nodeDef: [Object],
       elDef: [Object],
       elView: [Object] },
    ngErrorLogger: [Function: bound ] } ]

```

Whenever the key action popover is opened and Agent encounters an unknown scancode, instead of hitting this issue, set the key to none action, and behave normally.

**Comment by ert78gb** [comment]
How do you get the infinity loop?
I checked out the branch
I builded the code `npm run build`
I started the agent web `npm run server:web`
and the agent works fine.
If I delete the stored user-configuration from the browser local storage then also works without any problem.
I could modify the menu key on the mod layer. I could assign the menu KeyAction on other layer.

**Comment by mondalaci** [comment]
I can reproduce the issue with both the electron and web version. Please take the default configuration of the master branch, then use this branch and click on the key of the following image which should trigger the bug:

untitled

(Don't reset the configuration, because we don't want to make users reset their configuration.)

The console also shows the issue:

untitled2

**Comment by ert78gb** [comment]
I created a scan code validator. If the scan code not exists in scancodes.json then it will be replaced with NoneAction
I moved scancodes.json and seconderyRole.json files into the uhk-common package because the scancodes.json need to the validation

**Pull request merged**
