### PR TITLE
feat(app): Show add-on menu if start app with --addons arg

### LINKED ISSUE #351: Don't display the add-on modules by default
The add-on modules will only be implemented later until which point we shouldn't display them in the menu. Please hide them by default and only show them when the `--addons` command line argument is present.

### PR DESCRIPTION
**Pull request by ert78gb**
Close #351

### CODE REVIEW

**Comment by mondalaci** [comment]
Please resolve the conflict and I'll give it a try.

**Comment by ert78gb** [comment]
conflict resolved

**Comment by mondalaci** [comment]
I've tried it and `npm run electron --addons` doesn't reveal the add-ons menu for me. Any ideas why?

**Comment by ert78gb** [comment]
When use npm run you have to use -- to add command line argument.

npm run electron -- --addons

**Comment by mondalaci** [comment]
All good! The only reason I'm not merging this is that it's dependent on #338, so let's merge that first.

**Comment by ert78gb** [comment]
You could accept/merge this PR. #338 have to rebase and develop other issues.
I created the dependency linking but after the implementation is not relevant.

**Comment by ert78gb** [comment]
But now see I have to rebase this branch too

**Pull request merged**
