### PR TITLE
refactore: create feature modules

### LINKED ISSUE #96: Create feature modules
Since we have updated to angular 2 rc.6 our root module have come very large. We should create our own [feature modules](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#feature-modules).

### LINKED ISSUE #288: Display error message when permission set up fails
If permission setup / driver installation fails then display the return code and error message of the setup script below the "Set up permissions" button.

### LINKED ISSUE #326: Linux privilege escalation problem
Just after Agent escalates privilege on Linux, I hit a strange screen:

screenshot from 2017-06-28 20-51-02

First, I was totally clueless about what I saw, then opened the dev tools of Agent, dug into the HTML structure, and realized that I'm looking the ngrx/store Log Monitor.

This is the console log:

untitled

Luckily, the privilege escalation itself gets executed properly and if I restart Agent it can access the UHK over USB and doesn't display the privilege escalation screen anymore, but this error is definitely confusing.

It would be nice to get this fixed, and I'm especially interested about why the ngrx/store Log Monitor gets opened. We should always display the relevant errors to the user instead of displaying a developer tool.

### LINKED ISSUE #330: Remove libusb
After testing hidapi on Linux-64, Linux-32, Windows-64, Windows-32 and OSX, please remvove libusb and remove the extra abstraction layer that calls hidapi vs libusb.

Please also remove zadig, zadic, and generally speaking all the Windows specific privilege escalation code that has been obsoleted.

### LINKED ISSUE #361: Switching routes is very slow
When clicking on a menu item of the side menu I have to wait about a second for my Core i7 PC for the new page to appear which is a very long time. I'd like this to be vastly optimized.

### PR DESCRIPTION
**Pull request by ert78gb**
The PR is not fully ready, but I create to review.
The following bugs exists:
- ~~Device not connected content not vertically aligned -> will fix on Sunday~~
- ~~electron builder not working. -> will fix on Sunday~~
- ~~electron save user config -> will fix on Sunday~~
- circular dependencies -> I think @fjozsef could it fix easier than I. It is just a warning
- ~~currently send only the layer to the device. If I remember well @mondalaci wanna remove send keymap feature.~~
- ~~appveyor build not working~~

Summary:
- Introduced lerna package manager. Its manage the dependencies between modules.
- removes the lib usb library and code, close #330 
- Show error notification when set privilege failed, close #288 
- Remove ngrx-store-log-monitor, close #326 
- 'Switching routes is very slow' -> I tested it more than 20 times change between macro and keymap and I do not detect slowdown, close #361
- Source code structure
  packages
   - test-serializer
   - uhk-agent -> electron main content
   - uhk-common -> common content for web / electron renderer and electron main
   - uhk-web -> web / electron renderer content
   - usb

All UI code have been moved into the uhk-web package. 
All device communication code have been moved into uhk-agent folder. @mondalaci  **pls test the linux privilege escalation** 
Electron IPC module have been used to communicate between the electron-main and electron-renderer it will help to create AOT build if the circular dependencies will fix. 

If appveyor build failed with `Error: EPERM: operation not permitted` that is windows filesystem concurrency error, too much I/O operation for win :(

the PR close #96

### CODE REVIEW

**Comment by mondalaci** [comment]
I can confirm that sending the keymap to the device is not needed anymore.

This is clearly the biggest refactoring in the life of Agent, and I'm very impressed. I'm also hopelessly lost regarding the changeset. Hopefully @fjozsef has a better grasp on this, and a fair amount of time on his hands. :)

**Comment by mondalaci** [comment]
@ert78gb Which are the standing issues right now?

I can see 3 non-strikethough items in the list, but I can also see your "fix appveyor build" commit which should negate one of them, resulting in 2 standing issues. Please clarify.

**Comment by ert78gb** [comment]
I don't know what is the problem with appveyor. Yesterday I tried to find the solution, but no success :( I found posts maybe it is antivirus software lock problem .

The circular dependencies is a build warning

Electron builder - I could test it if building the code on appveyor

**Comment by ert78gb** [comment]
I am done and waiting for feedbacks

**Comment by mondalaci** [comment]
@fjozsef Agent-web builds with circular dependency warnings, but Agent-electron doesn't build. Is it normal?

```
laci@spark ~/projects/uhk/agent $ npm run build:electron

> uhk-agent@1.0.0 build:electron /home/laci/projects/uhk/agent
> run-s -sn build:electron:renderer build:electron:main


> uhk-agent@1.0.0 build:electron:renderer /home/laci/projects/uhk/agent/package.json
> lerna exec --scope uhk-web npm run build:renderer 

lerna info version 2.0.0
lerna info scope uhk-web
Hash: 61270040774c64f2651e                                                               
Version: webpack 3.4.1
Time: 13899ms
                                                  Asset     Size  Chunks                    Chunk Names
                                      scripts.bundle.js   255 kB       3  [emitted]  [big]  scripts
  glyphicons-halflings-regular.f4769f9bdb7466be6508.eot  20.1 kB          [emitted]         
  glyphicons-halflings-regular.e18bbf611f2a2e43afc0.ttf  45.4 kB          [emitted]         
 glyphicons-halflings-regular.fa2772327f55d8198301.woff  23.4 kB          [emitted]         
glyphicons-halflings-regular.448c34a56d699c29117a.woff2    18 kB          [emitted]         
           fontawesome-webfont.674f50d287a8c48dc19b.eot   166 kB          [emitted]         
           fontawesome-webfont.912ec66d7572ff821749.svg   444 kB          [emitted]  [big]  
           fontawesome-webfont.b06871f281fee6b241d6.ttf   166 kB          [emitted]         
         fontawesome-webfont.af7ae505a9eed503f8b8.woff2  77.2 kB          [emitted]         
          fontawesome-webfont.fee66e712a8a08eef580.woff    98 kB          [emitted]         
                                         main.bundle.js  1.34 MB       0  [emitted]  [big]  main
                                    polyfills.bundle.js   609 kB       1  [emitted]  [big]  polyfills
                                       styles.bundle.js   181 kB       2  [emitted]         styles
  glyphicons-halflings-regular.89889688147bd7575d63.svg   109 kB          [emitted]         
                                       vendor.bundle.js   3.1 MB       4  [emitted]  [big]  vendor
                                       inline.bundle.js  5.82 kB       5  [emitted]         inline
                                     main.bundle.js.map  1.61 MB       0  [emitted]         main
                                polyfills.bundle.js.map   735 kB       1  [emitted]         polyfills
                                   styles.bundle.js.map   236 kB       2  [emitted]         styles
                                  scripts.bundle.js.map   301 kB       3  [emitted]         scripts
                                   vendor.bundle.js.map  3.69 MB       4  [emitted]         vendor
                                   inline.bundle.js.map   5.9 kB       5  [emitted]         inline
                             assets/compiled_sprite.svg  70.4 kB          [emitted]         
                                     assets/favicon.ico  15.1 kB          [emitted]         
                           assets/images/agent-icon.png  2.65 kB          [emitted]         
                 assets/images/agent-logo-with-text.png  3.31 kB          [emitted]         
                                           ./index.html  1.37 kB          [emitted]         
[./node_modules/css-loader/index.js?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/index.js?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss] ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss 47.7 kB {2} [built]
[./src lazy recursive] ./src lazy 160 bytes {0} [built]
[./src/app/app.component.ts] ./src/app/app.component.ts 3.65 kB {0} [built]
[./src/environments/environment.ts] ./src/environments/environment.ts 499 bytes {0} [built]
[./src/main-renderer.ts] ./src/main-renderer.ts 559 bytes {0} [built]
[./src/polyfills.ts] ./src/polyfills.ts 2.85 kB {1} [built]
[./src/renderer/services/electron-datastorage-repository.service.ts] ./src/renderer/services/electron-datastorage-repository.service.ts 1.48 kB {0} [built]
[./src/renderer/services/electron-error-handler.service.ts] ./src/renderer/services/electron-error-handler.service.ts 1.52 kB {0} [built]
[./src/renderer/services/ipc-uhk-renderer.ts] ./src/renderer/services/ipc-uhk-renderer.ts 423 bytes {0} [built]
   [0] multi ./src/main-renderer.ts 28 bytes {0} [built]
   [1] multi ./src/polyfills.ts 28 bytes {1} [built]
   [2] multi script-loader!./node_modules/bootstrap/dist/js/bootstrap.js script-loader!./node_modules/select2/dist/js/select2.full.js 40 bytes {3} [built]
   [3] multi ./node_modules/bootstrap/dist/css/bootstrap.min.css ./src/styles.scss 40 bytes {2} [built]
[./src/renderer/uhk-renderer.module.ts] ./src/renderer/uhk-renderer.module.ts 2.43 kB {0} [built]
[./src/styles.scss] ./src/styles.scss 1.24 kB {2} [built]
    + 827 hidden modules
Child html-webpack-plugin for "index.html":
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 1.06 kB {0} [built]

> uhk-agent@1.0.0 build:electron:main /home/laci/projects/uhk/agent/package.json
> lerna exec --scope uhk-agent npm run build 

lerna info version 2.0.0
lerna info scope uhk-agent
ts-loader: Using typescript@2.4.2 and /home/laci/projects/uhk/agent/packages/uhk-agent/tsconfig.json
Hash: b3d884933a0576e68da5
Version: webpack 2.7.0
Time: 4229ms
               Asset       Size  Chunks                    Chunk Names
    electron-main.js    1.93 MB       0  [emitted]  [big]  main
electron-main.js.map    2.38 MB       0  [emitted]         main
       manifest.json  103 bytes          [emitted]         
        package.json  470 bytes          [emitted]         
  [13] ./~/rxjs/Observable.js 11.4 kB {0} [built]
  [22] ./~/electron-updater/out/main.js 4.68 kB {0} [built]
 [122] ./~/command-line-args/lib/output.js 4.47 kB {0} [built]
 [157] ./src/electron-main.ts 3.89 kB {0} [built]
 [222] /home/laci/projects/uhk/agent/~/electron-debug/index.js 2.19 kB {0} [built]
 [250] ./src/polyfills.ts 244 bytes {0} [built]
 [251] ./src/services/app-update.service.ts 4.17 kB {0} [built]
 [252] ./src/services/app.service.ts 1.16 kB {0} [built]
 [253] ./src/services/device.service.ts 5.75 kB {0} [built]
 [254] ./src/services/logger.service.ts 173 bytes {0} [built]
 [255] ./src/services/sudo.service.ts 2.01 kB {0} [built]
 [294] ./~/command-line-args/lib/argv.js 2.36 kB {0} [built]
 [295] ./~/command-line-args/lib/command-line-args.js 2.65 kB {0} [built]
 [411] ./~/sudo-prompt/index.js 30.5 kB {0} [built]
 [423] multi ./src/electron-main.ts 28 bytes {0} [built]
    + 409 hidden modules

WARNING in ../uhk-common/~/@angular/core/@angular/core.es5.js
5646:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ../uhk-common/~/@angular/core/@angular/core.es5.js
5662:15-102 Critical dependency: the request of a dependency is an expression

ERROR in /home/laci/projects/uhk/agent/packages/uhk-agent/node_modules/electron-updater/out/electron-updater.d.ts
(274,10): error TS1192: Module '"/home/laci/projects/uhk/agent/packages/uhk-agent/node_modules/bluebird-lst/index"' has no default export.
lerna ERR! exec Errored while executing 'npm run build' in 'uhk-agent'
lerna ERR! execute Error: Command failed: npm run build
lerna ERR! execute     at Promise.all.then.arr (/home/laci/projects/uhk/agent/node_modules/lerna/node_modules/execa/index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm run build
lerna ERR! execute     at Promise.all.then.arr (/home/laci/projects/uhk/agent/node_modules/lerna/node_modules/execa/index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna ERR! execute   stack: 'Error: Command failed: npm run build\n    at Promise.all.then.arr (/home/laci/projects/uhk/agent/node_modules/lerna/node_modules/execa/index.js:210:11)\n    at process._tickCallback (internal/process/next_tick.js:109:7)',
lerna ERR! execute   code: 2,
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: null,
lerna ERR! execute   stderr: null,
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm run build',
lerna ERR! execute   timedOut: false }

npm ERR! Linux 4.8.0-58-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:electron"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uhk-agent@1.0.0 build:electron: `run-s -sn build:electron:renderer build:electron:main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uhk-agent@1.0.0 build:electron script 'run-s -sn build:electron:renderer build:electron:main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uhk-agent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     run-s -sn build:electron:renderer build:electron:main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uhk-agent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uhk-agent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/laci/.npm/_logs/2017-08-14T19_31_15_319Z-debug.log
```

**Comment by ert78gb** [comment]
Circular dependencies warning do not block the build.

The following error more interest 
(274,10): error TS1192: Module '"/home/laci/projects/uhk/agent/packages/uhk-agent/node_modules/bluebird-lst/index"' has no default export.

Could you run the following command

npm run clean
npm i
npm run build
npm run electron

**Comment by mondalaci** [comment]
@ert78gb It works this way, indeed. Thanks for the instructions!

**Comment by mondalaci** [comment]
@ert78gb Unfortunately, I was on the master branch. Now that I use the branch of this PR I realized that the same problem persists.

**Comment by mondalaci** [comment]
Now that I use the correct node version it builds like a champ!

**Comment by fjozsef** [comment]
When I want to add a new keymap I can only add DVR.

**Comment by mondalaci** [comment]
Merged this PR and created #389 for the add keymap issue.

**Pull request merged**
