### PR TITLE
Add smart macro versioning queries.

### PR DESCRIPTION
**Pull request by kareltucek**

### CODE REVIEW

**Comment by mondalaci** [comment]
@ert78gb This PR got somehow accidentally closed, even though I don't remember closing it. Please review the code and add it to master.

**Comment by ert78gb** [comment]
@kareltucek can you reopen this PR or restore the branch or just open a new PR. The Reopen button is disabled for me thx.

**Comment by kareltucek** [comment]
> @ert78gb This PR got somehow accidentally closed

*Somehow*? You have deleted the target branch...

> @kareltucek can you reopen this PR or restore the branch or just open a new PR. The Reopen button is disabled for me thx.

Sure, will rebase it onto master and open a new PR.

**Comment by ert78gb** [comment]
Sorry, I don't remember

**Comment by ert78gb** [comment]
Sorry for the extra work if I made a mistake

**Comment by kareltucek** [comment]
> Sorry for the extra work if I made a mistake

No trouble and not much work actually, and there was no mistake on your side @ert78gb.

**Pull request closed without merging**
