### PR TITLE
feat(device): Read user config from eeprom

### PR DESCRIPTION
**Pull request by ert78gb**
I think we have to implement the loading screen #296 , because reading the whole eeprom is 5-6 sec. Until the end of reading white screen visible for the user.

close: #412, close: #410

### CODE REVIEW

**Comment by ert78gb** [comment]
I found a bug. It is not ready to review yet

**Comment by ert78gb** [comment]
@mondalaci ready to test

**Comment by mondalaci** [comment]
I cannot seem to be able to remap any keys now. When I remap a key it's displayed the same way as before.

**Comment by ert78gb** [comment]
Could you write step by step how do you test?

**Comment by mondalaci** [comment]
1. Start up Agent-electron.
2. Remap any key, for example try to remap the "A" key of the base layer of the QWERTY keymap to "B".
3. At this point, I'd expect the "A" letter to change to "B" but it's still shows "A".

(Strangely, when I click on the key and the popover appears, I can see "B" in select2 . So maybe it's changed in the data model, it's just not shown.)

**Pull request merged**
