### PR TITLE
Add new system scan codes

### PR DESCRIPTION
**Pull request by attilacsanyi**

### CODE REVIEW

**Comment by fjozsef** [comment]
@attilacsanyi 
Answering to https://github.com/UltimateHackingKeyboard/agent/issues/304#issuecomment-309502674 here, since it is more related to the PR.
The order in scancodes.json shouldn't matter. The type should be `system` and everything should work, if the id is unique. Could you clarify a bit more why is it not working for you?
I would like to keep the ascending order of the ids in the `scancodes.json` if it is possible.

**Comment by fjozsef** [comment]
@attilacsanyi I've fixed the bug in https://github.com/UltimateHackingKeyboard/agent/commit/b7b56ca49196afe3d99d2f0ef2c3ea876f7c6f6c

**Comment by mondalaci** [comment]
@attilacsanyi For me, the system keys get displayed above the media keys. Can you place them below the media keys?

**Comment by attilacsanyi** [comment]
System keys are now below media keys @mondalaci.
Let me know if I need to change any system icon from [icomoon](https://icomoon.io/#preview-ultimate).

**Comment by mondalaci** [comment]
@attilacsanyi Please use the 0844-switch icon for power and the 0346-bell3 icon for wake.

**Comment by attilacsanyi** [comment]
Icon change is pushed @mondalaci

**Comment by mondalaci** [comment]
@attilacsanyi Thanks, looks fine and dandy to me.

Any last words, @fjozsef?

**Pull request merged**
