### PR TITLE
Upgrade to ngrx v4

### PR DESCRIPTION
**Pull request by fjozsef**
ngrx to v4

### CODE REVIEW

**Comment by mondalaci** [comment]
Agent-electron fails for me:

untitled

**Comment by fjozsef** [comment]
@ert78gb Could you help with the migration? it seems runAfterBootstrap has changed. We'd need to use https://github.com/ngrx/platform/blob/master/docs/effects/api.md#onruneffects

**Comment by ert78gb** [comment]
of course. Could you pending this issue for 1-3 day . I think I will finish the feature module development and after I could help.
I think better if refactor the store in new module system.
Is it ok for you?

**Comment by fjozsef** [comment]
Sure, thanks.

**Comment by fjozsef** [comment]
It is blocked until ngrx-store-freeze is incompatible with NgRx 4.

**Comment by mondalaci** [comment]
Referencing the relevant issue: https://github.com/codewareio/ngrx-store-freeze/issues/17

**Comment by mondalaci** [comment]
According to the relevant NgRx issue, "Version 0.2.0 has been released with support for NgRx V4.x", so I'm removing the blocked tag.

@fjozsef Will you be able to wrap this up, or should @ert78gb finish it?

**Comment by fjozsef** [comment]
@mondalaci Unfortunatelly no, I don't think I will have time for it.

**Comment by mondalaci** [comment]
@fjozsef No problem at all. Assigning this to @ert78gb then.

**Comment by ert78gb** [comment]
this PR contains the solution of #406 issue.
close: #406

**Comment by mondalaci** [comment]
This doesn't look right:

untitled

I've checked out Agent and built it from the ground up, and I could reproduce the above empty state in both the electron and the web build.

**Comment by ert78gb** [comment]
I think I fix all bug

**Pull request merged**
