### PR TITLE
Select2 improvements

### PR DESCRIPTION
**Pull request by NejcZdovc**
This PR is resolving issue #84.

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@mondalaci please check it out

**Comment by mondalaci** [comment]
Looks like a million dollars, @NejcZdovc! There are some issues I've noticed:

* Alternate names like "PgDn" are not filtered.
* NumberPad -> Numpad
* MediaKeys -> Media Keys
* Spacebar -> Space
* Enter should be primary on the left side, and Return should be secondary on the right side instead of the other way around

**Comment by NejcZdovc** [comment]
All text mistakes are now fixed. Regarding filter there is sadly again no easy solution. We would need to add custom matching system You can read more about [here](https://select2.github.io/announcements-4.0.html#new-matcher). I can add it, but would need to add this functionality to wrapper. Would this feature be used only on this select2 for scan codes?

**Comment by mondalaci** [comment]
Thanks for updating the texts!

It'd be worth to add a custom matching callback, so that users could search for alternate names, too.

For the time being, we'd only use this feature for the scancode select2. My crystal ball is broken, so I'm not sure whether we'll use it for other select2 instances, too. :)

**Comment by NejcZdovc** [comment]
@mondalaci Ok, will also add this to the wrapper, but it will need to wait until more critical issues / tasks are done.

**Comment by NejcZdovc** [comment]
I split remaining task to to new task so we can close this PR.

**Comment by fjozsef** [comment]
left alignment
I think the left alignment should only be present on the Keypress tab and we should keep the default center alignment for the rest select2.
What do you think, @mondalaci ?

**Comment by NejcZdovc** [comment]
@fjozsef I agree with you. I prefer center align

**Comment by mondalaci** [comment]
Left align may look strange but I think it's because the width of the select2 widgets is overly large compared to the text content. How about reducing the width of select2 widgets to make them just slightly wider than the text content? Of course, we should maximize the width of select2 to fit within the popver.

**Comment by mondalaci** [comment]
I'd go as far as left-aligning the content of every select2 widgets. We could fully left align categories and leave some left padding for the items inside of the categories, thereby emphasizing hierarchy beyond bold/normal font weight. I'm not fully confident that this will work, I'm just saying that we should give it a try.

**Comment by mondalaci** [comment]
@NejcZdovc You're welcome to attach a couple of relevant screenshots. Maybe I'll come to the same conclusion.

**Comment by NejcZdovc** [comment]
@fjozsef we will stick with a left alignment and 100% width.

**Pull request merged**
