### PR TITLE
feat(notification): display app errors, close #319

### LINKED ISSUE #319: Display application errors
Let's use [angular-notifier](https://github.com/dominique-mueller/angular-notifier) to display application errors. Make the errors appear in the top right corner, slide them in from the right side, and use red background color.

Please check whether we can use use anything from #126. If neither this issue nor #318 can utilize #126 then close #126 and #74.

### PR DESCRIPTION
**Pull request by ert78gb**
Add angular-notifier module to show generic notification. This PR use #332 refactoring

### CODE REVIEW

**Comment by mondalaci** [comment]
Is there any way to test this? It'd be great to have a way.

**Comment by ert78gb** [comment]
yes, I am refactoring the auto updater error notifications

**Comment by mondalaci** [comment]
Cool! Please let me know when I'll be able to test this.

**Comment by ert78gb** [comment]
Morning you could test it. I create a separate PR for the refactoring.

**Pull request merged**
