### PR TITLE
Menu items highlight

### PR DESCRIPTION
**Pull request by NejcZdovc**
PR based on #129

### CODE REVIEW

**Comment by mondalaci** [comment]
Wow, this was quick! I noticed 2 issues.

1. When I delete a macro or keymap the menu item that automatically gets selected doesn't get highlighted.
2. The background color of the highlighted menu item is rather low contrast, making it hard for the user to notice it. How about using a darker color? Possibly the color of the right border of the side menu, so that it'd merge together with it visually?

**Comment by NejcZdovc** [comment]
1. This is because no macro is actually selected in menu. You are shown default macro page with first macro displayed from the list and because no ID is in the route, angular can't connect it to the macro. If this is something that is important, we can do work around.

2. Something like this:
image

**Comment by NejcZdovc** [comment]
New colour added for the active item.

**Comment by mondalaci** [comment]
The new menu item color seems to gel well with the UI.

I think it'd be a good idea to use the precise URL of the keymap/macro after deleting the previous one and highlight the relevant menu item accordingly.

I also noticed that when every macro gets deleted the empty state is the page that features the "To be done..." text. It'd make sense to display a helpful empty state like: "You don't have any macros. Try to add one!"

On a related note, I just noticed then if I have no macros then I cannot add a new one. The "To be done..." page is displayed instead of a new, empty macro upon trying to add a macro.

**Comment by NejcZdovc** [comment]
Regarding the text and macros. You need to wait for PR #127 to be merged. After that all problems should disappear 😃

**Comment by NejcZdovc** [comment]
I will create new issue where I will tackle this URL default states for keymap / macro.

**Comment by mondalaci** [comment]
Ah, sorry about my new macro comment. I'm getting lots in your PRs :)

**Comment by fjozsef** [comment]
Highlight is not working for the addon modules.

**Comment by NejcZdovc** [comment]
Added height light for addon modules as well. I wanted to left them out until we implement them fully, but sure not a problem.

**Pull request merged**
