### PR TITLE
Transfer the layer/keymap/config with node-usb on shortcuts

### LINKED ISSUE #213: Transfer the actual layer, keymap, config to the UHK over USB
Ctrl+u should make Agent transfer the binary configuration of the current layer to the UHK over USB. This calls for Electron and node-usb.

Ctrl+i should make Agent transfer the current keymap
Ctrl+o should make Agent transfer the whole configuration

No visual indication is necessary for the time being but console.logging what's being done would be useful.

@algernon is about to start with the configuration parser of the firmware soon, and this feature is very much necessary for him to rock and roll.

### PR DESCRIPTION
**Pull request by fjozsef**
Closes #213, #254 

Prerequisites:
On Linux, you'll need libudev to build libusb. On Ubuntu/Debian just run: `sudo apt-get install build-essential libudev-dev`

```
npm run build
npm run electron
```

### CODE REVIEW

**Comment by fjozsef** [comment]
@mondalaci @NejcZdovc I need feedback :)

**Comment by mondalaci** [comment]
@fjozsef No biggie, only 276 files are affected :D 

I'm not even sure what to check exactly regarding the UI/UX. Could you give me some idea?

**Comment by fjozsef** [comment]
Try to use both web and electron version.

**Comment by mondalaci** [comment]
@fjozsef All good! I've made Agent transfer the current layer to the UHK over USB with ctrl+U and it worked like a charm! The web build also works flawlessly. Well done!

**Pull request merged**
