### PR TITLE
Add legend for LED display font

### PR DESCRIPTION
**Pull request by danpalmer**
This PR is a work in progress, and a request for feedback on whether this feature would be welcomed, and on the approach taken.

While configuring my UHK I was excited to find that the LED display is quite flexible with many characters supported. However, exploring this took some trial and error. I thought a legend/key for the font would be a nice feature, to see what characters are supported and what each character looks like without flashing the keyboard.

Currently this is implemented as an extra page in the sidebar for demo purposes, but I think this would work well as a medium sized popover next to the input field for the LED display text. Additionally it might be nice to overlay the LED display component on the keyboard diagram with the selected text.

Thoughts and ideas welcome!

Screenshot 2022-07-30 at 15 27 29

### CODE REVIEW

**Comment by mondalaci** [comment]
Thanks for your contribution!

How would you exactly use this feature? I plan to [expose LEDs via a USB API](https://github.com/UltimateHackingKeyboard/firmware/issues/322), including the per-key RGB backlight and the LED display.

Although a nice touch, I feel uneasy about displaying the LED display in Agent, especially considering that future UHK will probably have much more sophisticated displays, and replicating them in Agent would take quite an effort.

**Comment by danpalmer** [comment]
@mondalaci My primary use-case here is having some sort of guide for what characters are available and what they'll look like.

As for how this is actually integrated, I'm open to ideas. I think a small popover next to the input may be the most subtle, while still providing some value. Alternatively perhaps there could be a live preview or something like that. Another option is to perhaps hide it somewhere in the "Help" screen. I don't think this needs to be prominent in any way, in fact I think the more out of the way the better so that it's only there for reference when really needed.

What do you think? If you think the guide is not a feature that makes sense in the agent that's absolutely fine, I'm happy to close this PR. If you think it could be useful somewhere though I'm happy to iterate and see if we can find somewhere good for it.

**Comment by mondalaci** [comment]
@danpalmer Thanks for elaborating on your use case! Based on customer feedback, we can see that some features are requested, but nobody has ever wanted to preview the content of the LED display, so I'd rather not merge this PR.

[This issue](https://github.com/UltimateHackingKeyboard/agent/issues/660) is the most relevant that is highly requested.

Given the above, I'm closing this PR. We appreciate your contribution regardless!

**Comment by danpalmer** [comment]
Cool, thanks for the consideration. I probably won't take a look at that issue as it's a bit more than I have time for and not something I'm personally interested in. I'll keep an eye open for other things while using the software though and may contribute more as I find things. It seems like a nice codebase to work in!

**Pull request closed without merging**
