### PR TITLE
Refactor: Replace NoneAction

### LINKED ISSUE #176: Keyactions
We are currently using array with specific ID's for key actions in keymap. We need to change this to objects and move this specific ID into object of the action.

This way we can manipulate array (add, remove) without any problems.

When this is done we can revert  #162.

### LINKED ISSUE #182: Replace NoneAction with null in JSON representation

### PR DESCRIPTION
**Pull request by fjozsef**
Fixes #182 

DataStorage should be cleared.

### CODE REVIEW

**Comment by fjozsef** [comment]
Should I rename `index` to `id`?

**Comment by mondalaci** [comment]
`id` reads good to me.

**Comment by NejcZdovc** [comment]
image

Why does is say backspace now, before it was just an arrow?

**Comment by NejcZdovc** [comment]
I would leave `index `here, because we are saving in this variable position on the keymap not ID of the keyaction.

**Comment by mondalaci** [comment]
Backspace was intentionally choosen because the left arrow looked ambiguous. It's not clear whether it means "cursor left" or backspace.

**Comment by fjozsef** [comment]
The backspace text was changed in #183. It has nothing to do with this PR.

**Comment by NejcZdovc** [comment]
I didn't see mentioned anywhere, that's why this was something new for me. Ok then there is just a mapping problem.

**Comment by fjozsef** [comment]
I had to downgrade the angular to the latest stable, because there was an error in the animation with the latest beta. (I couldn't find out if the bug is at our side or at their side.)

**Pull request closed without merging**
