### PR TITLE
Fixed color

### PR DESCRIPTION
**Pull request by NejcZdovc**
Fixing #110

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@fjozsef Please review

**Comment by mondalaci** [comment]
Looks good, but how about using a global color variable for this purpose?

**Comment by NejcZdovc** [comment]
I am not aware of a way to share global variables between different components. @fjozsef do you know how to achieve this?

**Comment by NejcZdovc** [comment]
How about if we create scss file with all definitions and then import it to the component scss?

**Comment by fjozsef** [comment]
In scss you also can [import](http://vanseodesign.com/css/sass-the-import-directive/) other (scss) files, so yould define the color in a global.scss and import it.

**Comment by NejcZdovc** [comment]
@mondalaci @fjozsef added variable and use it all around the app that blue color was used

**Comment by mondalaci** [comment]
I applaud the introduction of variables.scss but how about using a more descriptive variable name like `$normal-icon-highlight-color`? And then `$delete-icon-highlight-color` could also be introduced for the trash icon.

Also how about using `global-styles.scss`. It might be a more descriptive filename.

**Comment by NejcZdovc** [comment]
I am not a fan of so descriptive naming convention, because if we use this blue color for let's say link or title hover then you have variable for title named `...-icon-highlight-...`. I prefer naming convention like this:

- blue
- blue-dark
- blue-light
- blue-aero
- etc.

This way you can use color blue on multiple places. In my experience you have max 4 different shades of the same color in the project, otherwise you are doing something wrong :smile:

**Comment by mondalaci** [comment]
I see what you mean but it would be better to name variables in a semantic fashion for supreme maintainability. Let's say we want to change icon highlight color from blue to green. Then we'd have to rename loads of occurences versus one. That's why it'd be wise to use a semantic naming convention that is not related to the value of the variables.

**Comment by NejcZdovc** [comment]
Ok I see where are you coming from. How about if we merge both things in something like this:

### Solution 1
Icon -> `$icon`
Duplicate/Edit hover -> `$hover-icon`
Delete hover -> `$hover-icon-strong` (or something like this)
Link hover  -> `$hover-link`
Link -> $link

### Solution 2
Duplicate/Edit hover -> `$icon-hover`
Delete hover -> `$icon-hover-strong` (or something like this)
Link hover  -> `$link-hover`
Link -> `$link`

What do you think?

**Comment by mondalaci** [comment]
I vote for option 2. I'd rather use `$icon-hover-delete` instead of `$icon-hover-strong`. In my mind the more precisely we describe something the better it is.

**Comment by NejcZdovc** [comment]
Variable is now `$icon-hover`.

**Comment by NejcZdovc** [comment]
@fjozsef rebased to the master, please review

**Pull request merged**
