### PR TITLE
feat: sanity-check firmware files before updates

### LINKED ISSUE #608: Sanity-check firmware files before updates
Right now, the user can specify any file, and Agent will try to update the firmware with it. This deletes the  firmware of the right keyboard half, and times out the update process.

Agent should sanity-check the firmware image. The sanity check should be done before running the update process both for user provided firmware images and the bundled firmware image.

The sanity check should do the following:
1. Extract the tarball.
2. Read package.json
3. Check if the files described by `devices[*].source` exist.
4. Check if the files described by `modules[*].source` exist.

If the sanity check fails, pop up the "Invalid firmware file provided." error message.

### PR DESCRIPTION
**Pull request by ert78gb**
close #608

### CODE REVIEW

**Comment by mondalaci** [comment]
Please handle invalid package.json in a nicer way, just like missing devices and modules directories.

image

**Comment by ert78gb** [comment]
Pls share your firmware compressed file

**Comment by mondalaci** [comment]
[uhk-firmware-8.7.0-invalid-package-json.tar.gz](https://github.com/UltimateHackingKeyboard/agent/files/4022194/uhk-firmware-8.7.0-invalid-package-json.tar.gz)

**Comment by ert78gb** [comment]
added the invalid JSON handling

**Pull request merged**
