### PR TITLE
feat(device): Add 'Save to keyboard' button

### PR DESCRIPTION
**Pull request by ert78gb**
Created a 'Progress Button' that have 2 state in progress or not.
Able to set different text for different state:
- baseText for normal state
- progressText for in progress state

close: #377

### CODE REVIEW

**Comment by ert78gb** [comment]
@mondalaci When saving data to the keyboard is success should show the Success notification on the right top?

**Comment by mondalaci** [comment]
@ert78gb Nope, please only show notifications upon errors.

**Comment by ert78gb** [comment]
@mondalaci removed the success notification

**Comment by mondalaci** [comment]
The first save succeeds and works perfectly.

Unfortunately, the second save throws the following error:

untitled

Minor UI issues to be fixed:
1. Don't make the notification time out and disappear. Make it stay there until the user closes it. Make all notifications behave this way, not just this one.
2. When clicking on the Save to keyboard button, wait until the save is in progress. Then display "Saved!" and only then make the button leave the screen.

**Pull request merged**
