### PR TITLE
feat: Make the Agent application icon slightly smaller.

### PR DESCRIPTION
**Pull request by dgyimesi**
Do #896.

### CODE REVIEW

**Comment by ert78gb** [comment]
The electron builder uses the images from the `./builds` folder. These images used as icons in the desktop app. pls change these images too.

**Comment by dgyimesi** [comment]
I updated all sizes of Agent icons, however I don't have access to `iconutil` on Windows meaning that `agent/build/icon.icns` still needs to be updated on a Mac. @ert78gb can you help me out in this regard?

**Comment by ert78gb** [comment]
Ofcourse, I will create the `agent/build/icon.icns` tomorrow

**Comment by ert78gb** [comment]
I added the `agent/build/icon.icns` file.

**Pull request merged**
